const teamsDetails = {
  ams2: {
    palmares: [],
    list: [
      { name: 'Gachette', function: 'pilote / régleur' },
      { name: 'Dylan', function: 'pilote / régleur' },
      { name: 'Phenix28', function: 'pilote / régleur' },
      { name: 'Belli Courtoy', function: 'pilote / régleur' },
      { name: 'Lionel Broch', function: 'pilote / régleur' },
      { name: 'Seb', function: 'pilote / régleur' },
    ],
  },

  iRacing: {
    palmares: [],
    list: [
      { name: 'Frite', function: 'pilote / régleur' },
      { name: 'Cut', function: 'pilote / régleur' },
    ],
  },

  rFactor: {
    palmares: [],
    list: [{ name: 'Cut', function: 'pilote / régleur' }],
  },

  acc: {
    palmares: [
      '🏅 1x World Cup MESF national selection VBR France (Monaco 2022)',
    ],
    list: [
      { name: 'Merlve12', function: 'pilote / régleur' },
      { name: 'Elite59', function: 'pilote / régleur' },
      { name: '4cordes', function: 'pilote / régleur' },
      { name: 'Gachette', function: 'pilote / régleur' },
      { name: 'Siiwu', function: 'pilote / régleur' },
      { name: 'rics', function: 'pilote / régleur' },
      { name: 'Cut', function: 'pilote / régleur' },
    ],
  },

  gt: {
    palmares: [],
    list: [{ name: 'dejkoo92', function: 'pilote / régleur' }],
  },

  f1: {
    palmares: ['🏅 3x World final F1 Event Series'],
    list: [{ name: 'Zor', function: 'pilote / régleur' }],
  },

  rbr: {
    palmares: [
      '🏅 P4 France Team VBR (2021)',
      '🏅 P6 World Team VBR (2021)',
      '🏅 VBR Siiwu national selection Eesti',
    ],
    list: [
      { name: 'Vatanen38', function: 'pilote / régleur' },
      { name: 'Elite59', function: 'pilote / régleur' },
      { name: 'Benoit Granger', function: 'pilote / régleur' },
      { name: 'Gachette', function: 'pilote / régleur' },
      { name: 'InkAdd59', function: 'pilote / régleur' },
      { name: 'dejkoo92', function: 'pilote / régleur' },
      { name: 'Frite', function: 'pilote / régleur' },
      { name: 'ML7codriver', function: 'pilote / régleur' },
      { name: 'Julien Granger', function: 'pilote / régleur' },
      { name: 'Kuhej', function: 'pilote / régleur' },
      { name: 'Dieguin237', function: 'pilote / régleur' },
      { name: 'Re1pz', function: 'pilote / régleur' },
      { name: 'Siiwu', function: 'pilote / régleur' },
      { name: 'Cut', function: 'pilote / régleur' },
      { name: 'Kristofer', function: 'pilote / régleur' },
    ],
  },

  wrc: {
    palmares: [
      '🏅 1x World Final (2021)',
      '🏅 2x 3ème World Team VBR (2019 / 2020)',
      '🏅 P4 World Team VBR (2021)',
      '🏅 P5 World Team VBR (2022)',
    ],
    list: [
      { name: 'AutumnFuel', function: 'pilote / régleur' },
      { name: 'Chris34', function: 'pilote / régleur' },
      { name: 'Siiwu', function: 'pilote / régleur' },
      { name: 'Dieguin237', function: 'pilote / régleur' },
      { name: 'Napaverine', function: 'pilote / régleur' },
      { name: 'Oskar', function: 'pilote / régleur' },
      { name: 'élite59', function: 'pilote / régleur' },
      { name: 'InkAdd59', function: 'pilote / régleur' },
      { name: 'Billy', function: 'pilote / régleur' },
      { name: 'Raman Tojo Nirina', function: 'pilote / régleur' },
      { name: 'Thibou88', function: 'pilote / régleur' },
      { name: 'ROSSEL Y13', function: 'pilote / régleur' },
      { name: 'ML7codriver', function: 'pilote / régleur' },
      { name: 'Re1pz', function: 'pilote / régleur' },
      { name: 'djekoo92', function: 'pilote / régleur' },
      { name: 'YO83', function: 'pilote / régleur' },
      { name: 'AlexS2000', function: 'pilote / régleur' },
      { name: 'EdRosa', function: 'pilote / régleur' },
      { name: 'Cut', function: 'pilote / régleur' },
      { name: 'Tristan', function: 'pilote / régleur' },
      { name: 'DjGreg', function: 'pilote / régleur' },
      { name: 'Andyy', function: 'pilote / régleur' },
      { name: 'Rodyz', function: 'pilote / régleur' },
      { name: 'SilvaLM1979', function: 'pilote / régleur' },
      { name: 'Bullraza', function: 'pilote / régleur' },
    ],
  },

  dirt: {
    palmares: [
      '🏅 1x Demi Final World Series',
      '🏅 1x Quarter Final World Series',
    ],
    list: [
      { name: 'Vatanen38', function: 'pilote / régleur' },
      { name: 'Hugo Lnd', function: 'pilote / régleur' },
      { name: 'élite59', function: 'pilote / régleur' },
      { name: 'AutumnFuel', function: 'pilote / régleur' },
      { name: 'InkAdd59', function: 'pilote / régleur' },
      { name: 'Billy', function: 'pilote / régleur' },
      { name: 'Raman Tojo', function: 'pilote / régleur' },
      { name: 'Thibou88', function: 'pilote / régleur' },
      { name: 'ROSSEL Y13', function: 'pilote / régleur' },
      { name: 'PasquaM27', function: 'pilote / régleur' },
      { name: 'ML7codriver', function: 'pilote / régleur' },
      { name: 'Re1pz', function: 'pilote / régleur' },
      { name: 'djekoo92', function: 'pilote / régleur' },
      { name: 'YO83', function: 'pilote / régleur' },
      { name: 'AlexS2000', function: 'pilote / régleur' },
      { name: 'EdRosa', function: 'pilote / régleur' },
      { name: 'Cut', function: 'pilote / régleur' },
      { name: 'Tristan', function: 'pilote / régleur' },
      { name: 'Andyy', function: 'pilote / régleur' },
      { name: 'Rodyz', function: 'pilote / régleur' },
      { name: 'SilvaLM1979', function: 'pilote / régleur' },
      { name: 'Bullraza', function: 'pilote / régleur' },
    ],
  },

  rx: {
    palmares: ['🏅 2x Quarter Final World Series'],
    list: [
      { name: 'DONOVAN', function: 'pilote / régleur' },
      { name: 'Elite59', function: 'pilote / régleur' },
      { name: 'InkAdd59', function: 'pilote / régleur' },
      { name: 'ArVaLa', function: 'pilote / régleur' },
      { name: 'Jerem81', function: 'pilote / régleur' },
      { name: 'AlexS2000', function: 'pilote / régleur' },
      { name: 'Gachette', function: 'pilote / régleur' },
      { name: 'Dylan', function: 'pilote / régleur' },
      { name: 'phenix28', function: 'pilote / régleur' },
      { name: 'Belli Courtoy ', function: 'pilote / régleur' },
      { name: 'Lionel Broch', function: 'pilote / régleur' },
      { name: 'Seb', function: 'pilote / régleur' },
      { name: 'MATPAIN', function: 'pilote / régleur' },
    ],
  },

  all: {
    palmares: [],
    list: [
      { name: 'AutumnFuel', function: 'FRA' },
      { name: 'CHRIS34', function: 'FRA' },
      { name: 'Hugo Lnd', function: 'FRA' },
      { name: 'Vatanen38', function: 'FRA' },
      { name: 'élite59', function: 'FRA' },
      { name: 'InkAdd59', function: 'FRA' },
      { name: 'DjGreg2b', function: 'FRA' },
      { name: 'Billy', function: 'BEL' },
      { name: 'Raman Tojo', function: 'MG' },
      { name: 'Thibou88', function: 'FRA' },
      { name: 'ROSSEL Y13 ', function: 'FRA' },
      { name: 'Pasqua M27', function: 'FRA' },
      { name: 'Merlve12', function: 'FRA' },
      { name: 'DONOVAN', function: 'FRA' },
      { name: 'ArVaLa', function: 'FRA' },
      { name: '4cordes', function: 'FRA' },
      { name: '82mai28', function: 'POL' },
      { name: 'ML7codriver', function: 'FRA' },
      { name: 'Siiwu', function: 'EST' },
      { name: 'Benoit Granger', function: 'FRA' },
      { name: 'Jerem81', function: 'FRA' },
      { name: 'Gachette', function: 'FRA' },
      { name: 'Dieguin237', function: 'ESP' },
      { name: 'Re1pz', function: 'EST' },
      { name: 'djekoo92', function: 'SLO' },
      { name: 'YO83', function: 'FRA' },
      { name: 'AlexS2000', function: 'FRA' },
      { name: 'Frite', function: 'BEL' },
      { name: 'Julien Granger', function: 'FRA' },
      { name: 'kuhej', function: 'SLO' },
      { name: 'Oskar', function: 'EST' },
      { name: 'EdRosa', function: 'BRE' },
      { name: 'rics', function: 'FRA' },
      { name: 'Kristofer', function: 'BEL' },
      { name: 'Cut', function: 'FRA' },
      { name: 'Dylan', function: 'FRA' },
      { name: 'phenix28', function: 'FRA' },
      { name: 'Lionel Broch ', function: 'FRA' },
      { name: 'Belli Courtoy', function: 'ITA' },
      { name: 'Tristan', function: 'FRA' },
      { name: 'Seb', function: 'FRA' },
      { name: 'MATPAIN', function: 'FRA' },
      { name: 'Napaverine', function: 'THL' },
      { name: 'Andyy', function: 'EST' },
      { name: 'Rodyz', function: 'FRA' },
      { name: 'SilvaLM1979', function: 'FRA' },
      { name: 'Bullraza', function: 'ITA' },
    ],
  },
};

export default teamsDetails;
